{% set name = "pynvim" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed99cbaf286998aad48564ae13d26933b9106fc5a917a719798d2f2b2b8683ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.4
    - pytest-runner
    - pip
  run:
    - python >=3.4
    - msgpack-python >=0.5.0
    - greenlet

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pynvim
    - pynvim.api
    - pynvim.msgpack_rpc
    - pynvim.msgpack_rpc.event_loop
    - pynvim.plugin

about:
  home: http://github.com/neovim/pynvim
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client to neovim

  description: |
    Python client to neovim
  dev_url: https://github.com/neovim/pynvim

extra:
  recipe-maintainers:
    - curtisalexander
    - xhochy
